export { default as authRouter } from "./auth"
export { default as userRouter } from "./user"
export { default as adminRouter } from "./admin"
export { default as productRouter } from "./product"
export { default as cartRouter } from "./cart"
export { default as categoryRouter } from "./category"
